version: '2'
services:
  pfumv10-app:
    image: pfumv10
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://pfumv10-mysql:3306/pfumv10?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://pfumv10-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://pfumv10-elasticsearch:9200
    ports:
      - 8080:8080
  pfumv10-mysql:
    extends:
      file: mysql.yml
      service: pfumv10-mysql
  pfumv10-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: pfumv10-elasticsearch
